[package]
name = "orx-concurrent-queue"
version = "0.1.0"
edition = "2024"

[dependencies]
orx-pinned-vec = { git = "https://github.com/orxfun/orx-pinned-vec", branch = "concurrent-queue-support" }
orx-split-vec = { git = "https://github.com/orxfun/orx-split-vec", branch = "support-for-concurrent-queue" }
orx-fixed-vec = { git = "https://github.com/orxfun/orx-fixed-vec", branch = "support-for-concurrent-queue" }
exponential-backoff = { version = "2.1.0" }

[dev-dependencies]
criterion = { version = "0.7.0", default-features = false }
orx-concurrent-bag = { version = "3.1.0" }
test-case = { version = "3.3.1" }
